version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000 
    # we can pass file of environment variables or pass an array of envs
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=fastapi
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=36000
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
