version: "3"
services:
  api:
    image: n00rs/fastapi
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    # command: fastapi run app/main.py --host 0.0.0.0 --port 8000 
    # we can pass file of environment variables or pass an array of envs
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
