"""auto genrate tbl_vote

Revision ID: 3533c43d5452
Revises: 86da2737baf5
Create Date: 2025-02-28 00:20:02.435350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3533c43d5452'
down_revision: Union[str, None] = '86da2737baf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vote',
    sa.Column('int_user_id', sa.Integer(), nullable=False),
    sa.Column('int_post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['int_post_id'], ['tbl_post.int_post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['int_user_id'], ['tbl_user.int_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('int_user_id', 'int_post_id')
    )


def downgrade() -> None:
    op.drop_table('tbl_vote')
